name: 'Utilities Meters'
description: 'Submit electricity and gas meter readings'
version: '1.1.1'
slug: 'utilities_meters'
init: false
arch:
  - aarch64
  - amd64
host_network: true
options:
  node_env: 'development'
  electricity_base_url: ''
  electricity_account_number: ''
  gas_base_url: ''
  gas_account_number: ''
  gas_building_number: ''
  gas_owner_name: ''
  gas_captcha_api_key: ''
schema:
  node_env: 'list(development|production)'
  electricity_base_url: str?
  electricity_account_number: str?
  gas_base_url: str?
  gas_account_number: str?
  gas_building_number: str?
  gas_owner_name: str?
  gas_captcha_api_key: str?
